name = "TwoStepPECE"
uuid = "a3249742-8b8e-47cf-84bc-ddc0aab4d667"
version = "0.1.0"
authors = ["AlanFreed <alan.d.freed@proton.me>"]

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PhysicalFields = "ecb0663d-aa47-424e-b5ff-03a0dca9671a"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
JSON3 = "1.14.3"
LinearAlgebra = "1.12.0"
PhysicalFields = "1.3.1"
StructTypes = "1.11.0"
